ALTER TABLE "work_days" ADD COLUMN IF NOT EXISTS "break_start" TIMESTAMP(3);
ALTER TABLE "work_days" ADD COLUMN IF NOT EXISTS "break_type" TEXT;
ALTER TABLE "work_days" ADD COLUMN IF NOT EXISTS "break_minutes" INTEGER NOT NULL DEFAULT 0;